### ISSUE TITLE
[Feature request] change directory names

### ISSUE THREAD

**Issue by powerdude** [mikenye/docker-youtube-dl#11]
Hello, 

Could you possibly change the configuration so that configs files can be in one directory and videos be in another.  So, your example on the readme could look like this:

```
docker run \
    --rm -i \
    -e PGID=$(id -g) \
    -e PUID=$(id -u) \
    -v /path/to/downloaded/videos:/videos:rw \
    -v /path/to/youtube-dlc/config:/etc/youtube-dlc/config:ro \
    -v /path/to/youtube-dlc/data:/etc/youtube-dlc/data:rw \
    mikenye/youtube-dl
```

I currently have to specify a volume mapping for each of the youtube files like .netrc, .youtube-dl-archive, etc. because i don't want them to be in the videos/workdir/subscriptions directory.

**Comment by mikenye** [comment]
Duplicate of issue #12
