### ISSUE TITLE
Uses Python 2 rather than Python 3

### ISSUE THREAD

**Issue by jmburges** [mikenye/docker-youtube-dl#18]
Rather odd bug, but it looks like Python 2 is what is running youtube-dl, rather than python 3. I know you install python 3, but in the log from youtube-dl, it says it's running off of python 2 as you can see here:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'bestaudio[ext=m4a]', u'--add-metadata', u'-v', u'https://www.bbc.co.uk/sounds/play/m000qwyj']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2021.01.08
[debug] Python version 2.7.16 (CPython) - Linux-3.16.85-62-aarch64-with-debian-10.7
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] m000qwyj: Downloading video page
```

Any ideas?

**Comment by jmburges** [comment]
I ran the shell within the docker container and can confirm that the `python` command gives 2.7.16, and the `python3` command gives 3.7.3

**Comment by jmburges** [comment]
Also of course thank you for making this!

**Comment by mikenye** [comment]
Hi @jmburges,

I've updated the container to use python3.

Images are currently building and should be pushed to dockerhub within the hour.

Thanks!

-Mike

**Comment by mikenye** [comment]
You can view progress here: https://github.com/mikenye/docker-youtube-dl/actions/runs/484302491
