### ISSUE TITLE
403 forbidden due to no tls 1.3 support

### ISSUE THREAD

**Issue by Timtam** [mikenye/docker-youtube-dl#23]
Hello,

some pages (like crunchyroll) are dishing out 403 forbidden responses when trying to download via youtube-dl recently. The issue seems to be that either TLS 1.3 isn't enabled by the system or the Python version used is too old. Some people seem to succeed when using Python 3.8.2. Could you check this out and see if you can do something about this container-side?
https://github.com/ytdl-org/youtube-dl/issues/25481
Thanks. I do have a setup to reproduce this issue, so let me know if I can test something for you or help in some other way.

**Comment by mikenye** [comment]
Hi @Timtam, could I trouble you to pull the latest version of the container, and let me know if this problem still persists?

**Comment by mikenye** [comment]
The version of python in the latest container definitely supports TLS v1.3.

Can you please try this:

```
docker pull mikenye/youtube-dl
docker run --rm -i -e PGID=$(id -g) -e PUID=$(id -u) -v "$(pwd)":/workdir mikenye/youtube-dl --verbose --user-agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/76.0' 'https://www.crunchyroll.com/digimon-adventure-2020/episode-51-the-mystery-hidden-within-the-crests-810125'
```

There's reports that crunchroll requires an individual episode to be selected, rather than downloading a whole show.

Reference: https://github.com/ytdl-org/youtube-dl/issues/25437

**Comment by Timtam** [comment]
Okay, so I tested this and it works (reporting me that there only is a preview available right now). I then went ahead and tried downloading the entire show - works as well. I then thought, lets update my automated job and see if this will work - it doesn't. Huh? I then tried downloading the entire show with the same command again - it failed this time. Then the single episode - works, and the full show, works as well. Sounds rather confusing ...
So, what works right now, is:

* Download single episode first
* Download the entire show directly afterwards

What does not work:

* Download the entire show from the start
* Downloading more than one full show after trying to download a single episode, or waiting too long between the single episode and a full show download

Really weird...

**Comment by mikenye** [comment]
If you take a look at the youtube-dl case I referenced above - you'll see that the problem is the CloudFlare DDoS protection  that CrunchyRoll employ. I don't think I'm going to be able to do much better than this - we're at the mercy of the youtube-dl devs.

**Comment by Timtam** [comment]
Yep, you're right. Thanks for updating to python 3.9 though, thats pretty nice.

**Comment by mikenye** [comment]
That was @Kagami's handiwork :-)
