### ISSUE TITLE
UMASK setting

### ISSUE THREAD

**Issue by Kagami** [mikenye/docker-youtube-dl#25]
Hi,

Great docker.
Would be nice to have a setting for UMASK, similar to PUID and PGUI variables.
So that you can control what permissions downloaded files have. By default it's 022 which isn't always appropriate.

Thanks.

**Comment by mikenye** [comment]
Unfortunately `youtube-dl` doesn't have an option to set a umask variable, so this would be difficult to implement reliably.

What you could do, is use `youtube-dl`'s `--exec` argument to run a `chmod` on the downloaded file to set your desired permissions:

```
--exec CMD                           Execute a command on the file after
                                     downloading and post-processing,
                                     similar to find's -exec syntax.
                                     Example: --exec 'adb push {}
                                     /sdcard/Music/ && rm {}'
```

Is that an acceptable workaround until `youtube-dl` supports setting a umask?

**Comment by Kagami** [comment]
I've just tried and `setpriv` seems to inherit `UMASK` just fine from the parent shell. Can't we set it in `init` script?

```bash
$ umask
0022
$ setpriv --reuid test --regid test --init-groups bash -c 'umask'
0022
$ umask 077
$ setpriv --reuid test --regid test --init-groups bash -c 'umask'
0077
```

**Comment by mikenye** [comment]
I didn't think to try this... 🤦 

Sure thing - I will implement this now.

**Comment by mikenye** [comment]
Just waiting for tests to complete, then will merge #29

**Comment by Kagami** [comment]
Great, thanks you!

**Comment by mikenye** [comment]
Deployment job is running, it should be ready once these finish: https://github.com/mikenye/docker-youtube-dl/actions/runs/927818402
