### ISSUE TITLE
Download fresh youtube-dl on start

### ISSUE THREAD

**Issue by Kagami** [mikenye/docker-youtube-dl#27]
Should be easy to download latest youtube-dl build in `init` script (or run `youtube-dl -U`) so that users can just restart containers for update. Might be useful in case of often API breakages, sometimes youtube-dl has few releases per day.

What do you think?

**Comment by mikenye** [comment]
Maybe an environment variable such as `UPDATE_YOUTUBE_DL` that the user can set which would run `youtube-dl -U` as a cont-init.d job...

**Comment by mikenye** [comment]
Implemented via environment variable, and readme updated.

Just set the environment variable `UPDATE_YOUTUBE_DL` to any value, and `youtube-dl` will be run on container start.

**Comment by Kagami** [comment]
Perfect, thanks. I will try it.
