### ISSUE TITLE
Error with --xattrs

### ISSUE THREAD

**Issue by alscaldas** [mikenye/docker-youtube-dl#30]
Hi @mikenye 

First off I'd like to congratulate you for this docker container. I've been using it for a while and it's been a pretty positive experience.

The thing is I found an interesting parameter, "--xattrs", which allow youtube-dl to write  additional metadata as file attributes after download the videos. But when I try to use it with your container I get the following message:

`ERROR: Couldn't find a tool to set the xattrs. Install either the python 'pyxattr' or 'xattr' modules, or the GNU 'attr' package (which contains the 'setfattr' tool).`

I believe that if your image had one of these modules would solve this issue.

Would you please add this in the next versions of your images?

I'd be much appreciated. Thanks.

**Comment by mikenye** [comment]
Hi @alscaldas, are you able to pull the latest version and let me know if xattrs is working as expected? Thanks!

**Comment by alscaldas** [comment]
> Hi @alscaldas, are you able to pull the latest version and let me know if xattrs is working as expected? Thanks!

Hello @mikenye 

Just to let you know that this latest version works like a charm!
Thank you so much for the prompt reply and to take the time to look into this issue.

**Comment by mikenye** [comment]
You’re most welcome. Thanks for testing!
