### ISSUE TITLE
Switch To YT-DLP?

### ISSUE THREAD

**Issue by kyleinprogress** [mikenye/docker-youtube-dl#32]
I was trying to use your container and was having issues downloading videos from my subscriptions. After a bit of debugging, it's apparently a known issue with youtube-dl. Looking a little deeper, youtube-dl hasn't been updated in almost 2 months and the last release is from June. Given that they historically released updates weekly (if not more), I'm starting the think the project is dying off.

[YT-DLP](https://github.com/yt-dlp/yt-dlp) has taken over and is staying on top off issues and PRs.

**Comment by revilo951** [comment]
https://github.com/mikenye/docker-youtube-dl/pull/34
