### ISSUE TITLE
issue after latest update yt-dlp: error: option --fixup:

### ISSUE THREAD

**Issue by hppyworld** [mikenye/docker-youtube-dl#35]
youtube-dl-cron    | yt-dlp: error: option --fixup: invalid choice: 'fix' (choose from 'never', 'ignore', 'warn', 'detect_or_warn', 'force')

there is a issue after update to latest version. before it was working fine. 
can you please tell me how to fix it ?

thanks

**Comment by mikenye** [comment]
You need to specify a policy after `--fixup`.

According to the yt-dlp documentation:

```
    --fixup POLICY                   Automatically correct known faults of the
                                     file. One of never (do nothing), warn (only
                                     emit a warning), detect_or_warn (the
                                     default; fix file if we can, warn
                                     otherwise), force (try fixing even if file
                                     already exists)
```

So, depending on what you're trying to do, you either want to put `warn`, `detect_or_warn` or `force` after `--fixup`.

You likely want `detect_or_warn`.
