### ISSUE TITLE
About GID/PID permissions

### ISSUE THREAD

**Issue by chopinsong** [mikenye/docker-youtube-dl#4]
hello,I'm in trouble.
When I execute using root, the response is:

```
Addgroup: The GID '0' is already in use.
Adduser: The UID 0 is already in use.
Setpriv: failed to parse reuid: 'dockeruser'
```

When I use another user or another ID, the response is:

```
File: index - index. Mp4, part: Permission denied
```

**Comment by mikenye** [comment]
Hi @chopinsong, could you please post:

- the command line you used
- `cd` to the directory where you tried to run the container, and post the output of `ls -ladn .`

Thanks.

**Comment by chopinsong** [comment]
I configure Quick Start based on the documentation ==> ~/.bashrc:
alias youtube-dl='docker run \
                  --rm -i \
                  -e PGID=$(id -g) \
                  -e PUID=$(id -u) \
                  -v "$(pwd)":/workdir:rw \
                  mikenye/youtube-dl'

and command line :
 youtube-dl url 

and output:
[root@chopin xmd]# ls -ladn .
drwxr-xr-x 3 0 0 4096 Jun  2 09:44 .

**Comment by mikenye** [comment]
Do you have a non-root user account that you normally use?

If so can you log on as this account and post the output of the `id` command?

**Comment by mikenye** [comment]
I would encourage you to change your filesystem permissions and not run the container as root.

If you need some help with this, respond here.
