### ISSUE TITLE
ghrc.io unauthorized

### ISSUE THREAD

**Issue by milleraa** [mikenye/docker-youtube-dl#45]
HI
I've added alias and tried to download video.

I've got the error 
`docker: Error response from daemon: Head "https://ghcr.io/v2/mikenye/docker-youtube-dl/manifests/latest": unauthorized.`

How can I resolve it?

**Comment by simonbowen** [comment]
Also getting this issue, tried to authorize using

`echo '<my_token>' | docker login ghcr.io -u <my_username> --password-stdin`

**Comment by mikenye** [comment]
Apologies for this, it should be fixed now. Please let me know if you're still having issues and I will re-open this issue and investigate further.
