### ISSUE TITLE
Upgrade to  2020.06.16.1?

### ISSUE THREAD

**Issue by powerdude** [mikenye/docker-youtube-dl#5]
Hi,

I was wondering if you were planning on upgrading to the latest version or not.  I'm trying to run your container and it seems to be getting an error that is supposed to be fixed in the latest version.  Any guidance would be greatly appreciated.

`
ERROR: u'content_html'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 969, in process_ie_result
    ie_entries, playliststart, playlistend))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 313, in _entries
    content_html = more['content_html']
KeyError: u'content_html'
`

**Comment by mikenye** [comment]
Yes, this should be ready now!

I actually have a nightly build that runs, so that new versions are built and pushed automatically, however the build process was being cached. I’ve fixed this by preventing build caching. 

Thanks for reporting!

**Comment by powerdude** [comment]
Everything seems to be good now.  Thanks!

**Comment by mikenye** [comment]
No problems! Cheers.
